name: 'Gather_hs6_backfill'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'


env:
  zip: CNP_6_history
  fill_zero_bit: 6
  mappings_path: "./tmp/mappings.json"
  github_repo: "https://github.com/CECNdata/CNP_feed_HS46_all.git"

permissions: write-all

jobs:
  Gather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install sshpass -y
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt
          rm requirements.txt
      - name: Do the gather
        run: |
          git clone ${github_repo} tmp
          for file in `ls -d tmp/*Customs*HS6*`;do (base_dir=${file} python3 gather.py);done
          for f in *HS6*.csv; do mv "$f" "$(echo "$f" | sed -E 's/CNP-Customs-total-HS6-(export|import)-(RMB|USD)_([0-9]{4})_([0-9]{2})\.csv/hs6_\L\2\E_\1_all_\3\4\4_001.csv/' | sed -E 's/export/exp/; s/import/imp/;')"; done
          ls -la ./
          
      - name: FTP upload
        continue-on-error: true
        run: |
          export filename=${{ env.zip }}.zip
          zip -r ${filename} *HS6*.csv 
      #    echo "put ${filename} ${{ secrets.CNP_8_HISTORY }}" |  SSHPASS='${{ secrets.FTP_PASS }}' sshpass -e sftp -P ${{ secrets.FTP_PORT }} -o "HostKeyAlgorithms=+ssh-rsa"  -o "StrictHostKeyChecking=no" ${{ secrets.FTP }}  2> >(grep -v "ftp" 1>&2)

      #- name: FTP upload twice
      #  continue-on-error: true
      #  run: |
      #    export filename=${{ env.zip }}.zip
      #    echo "put ${filename} ${{ secrets.CNP_8_HISTORY }}" |  SSHPASS='${{ secrets.FTP_PASS }}' sshpass -e sftp -P ${{ secrets.FTP_PORT }} -o "HostKeyAlgorithms=+ssh-rsa"  -o "StrictHostKeyChecking=no" ${{ secrets.FTP }}  2> >(grep -v "ftp" 1>&2)

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gathered-data
          path: ${{ env.zip }}.zip
          retention-days: 7
