name: 'Gather_hs46_backfill'

on:
  workflow_dispatch:



env:
  github_repo: "https://github.com/CECNdata/CNP_feed_HS46_all.git"

permissions: write-all

jobs:
  Gather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install sshpass zsh -y
          pip install pipreqs
          pipreqs .
          pip install -r requirements.txt
          rm requirements.txt
      - name: Do the gather
        run: |
          export month_range="${month_range:-3}"
          git clone ${github_repo} tmp
          for file in `ls -d tmp/*Customs*HS*`;do (base_dir=${file} python3 gather_backfill.py);done
          ls -la ./latest_backfill
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gathered-latest-data
          path: "./latest_backfill/*.csv"
          retention-days: 7
